<?php
$title = 'Thêm khóa học';
$this->headTitle($title);

?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

//mã lĩnh vực
$makh = $form->get('Makh');
$makh->setAttribute('class', 'form-control');
$makh->setAttribute('placeholder', 'Mã khóa học');

// tên lĩnh vực
$tenkh = $form->get('Tenkh');
$tenkh->setAttribute('class', 'form-control');
$tenkh->setAttribute('placeholder', 'Tên khóa học');

$thoigian = $form->get('Thoigian');
$thoigian->setAttribute('class', 'form-control');
$thoigian->setAttribute('placeholder', 'Thời gian');
//ghi chú
$ghichu = $form->get('Ghichu');
$ghichu->setAttribute('class', 'form-control');
$ghichu->setAttribute('placeholder', 'Ghi chú');

// submit
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('linhvuc', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($makh) ?>
        <?= $this->formElement($makh) ?>
        <?= $this->formElementErrors()->render($makh, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($tenkh) ?>
        <?= $this->formElement($tenkh) ?>
        <?= $this->formElementErrors()->render($tenkh, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($thoigian) ?>
        <?= $this->formElement($thoigian) ?>
        <?= $this->formElementErrors()->render($thoigian, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($ghichu) ?>
        <?= $this->formElement($ghichu) ?>
        <?= $this->formElementErrors()->render($ghichu, ['class' => 'help-block']) ?>
    </div>


<?php
echo $this->formSubmit($submit);

echo $this->form()->closeTag();