<?php
$title = 'Thêm giảng viên';
$this->headTitle($title);

?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

//mã lĩnh vực
    $magv = $form->get('Magv');
    $magv->setAttribute('class', 'form-control');
    $magv->setAttribute('placeholder', 'Mã giảng viên');

    // tên lĩnh vực
    $tengv = $form->get('Tengv');
    $tengv->setAttribute('class', 'form-control');
    $tengv->setAttribute('placeholder', 'Tên giảng viên');
    //ghi chú

    $namsinh = $form->get('Namsinh');
    $namsinh->setAttribute('class', 'form-control');
    $namsinh->setAttribute('placeholder', 'Năm sinh');

    $gioitinh = $form->get('Gioitinh');
    $gioitinh->setAttribute('class', 'form-control');
    $gioitinh->setAttribute('placeholder', 'Giới tính');

    $hocvi = $form->get('Hocvi');
    $hocvi->setAttribute('class', 'form-control');
    $hocvi->setAttribute('placeholder', 'Học vị');

    $email = $form->get('Email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('placeholder', 'Email');

    $dienthoai = $form->get('Dienthoai');
    $dienthoai->setAttribute('class', 'form-control');
    $dienthoai->setAttribute('placeholder', 'Điện thoại');

    $diachi = $form->get('Diachi');
    $diachi->setAttribute('class', 'form-control');
    $diachi->setAttribute('placeholder', 'Địa chỉ');
    // submit
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('giangvien', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($magv) ?>
        <?= $this->formElement($magv) ?>
        <?= $this->formElementErrors()->render($magv, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($tengv) ?>
        <?= $this->formElement($tengv) ?>
        <?= $this->formElementErrors()->render($tengv, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($namsinh) ?>
        <?= $this->formElement($namsinh) ?>
        <?= $this->formElementErrors()->render($namsinh, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($gioitinh) ?>
        <?= $this->formElement($gioitinh) ?>
        <?= $this->formElementErrors()->render($gioitinh, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($hocvi) ?>
        <?= $this->formElement($hocvi) ?>
        <?= $this->formElementErrors()->render($hocvi, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($dienthoai) ?>
        <?= $this->formElement($dienthoai) ?>
        <?= $this->formElementErrors()->render($dienthoai, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($diachi) ?>
        <?= $this->formElement($diachi) ?>
        <?= $this->formElementErrors()->render($diachi, ['class' => 'help-block']) ?>
    </div>


<?php
echo $this->formSubmit($submit);

echo $this->form()->closeTag();